const COACH_COUNT_RANGE = { min: 2, max: 5 };
const COACH_NAME_COUNT_RANGE = { min: 2, max: 4 };
const UNAVAILABLE_MENU_COUNT_RANGE = { min: 0, max: 2 };

exports.COACH_COUNT_RANGE = COACH_COUNT_RANGE;
exports.COACH_NAME_COUNT_RANGE = COACH_NAME_COUNT_RANGE;
exports.UNAVAILABLE_MENU_COUNT_RANGE = UNAVAILABLE_MENU_COUNT_RANGE;
